version: '3.7'

services:
 app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: VendaOnline
    ports:
      - 8081:8081
    volumes:
      - ./:/home/app/
    networks:
      - app-network


networks:
  app-network:
    driver: bridge